networks:
  net:
    driver: bridge

services:
  app:
    networks:
      - net
    build: .
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: .
          target: /app

  db:
    image: postgres:latest
    networks:
      - net
    environment:
      POSTGRES_USER: sigap
      POSTGRES_DB: sigap_bd
      POSTGRES_PASSWORD: sigap
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sigap -d sigap_bd" ]
      interval: 10s
      retries: 5

volumes:
  postgres_data:
