networks:
  net:

services:
  app:
    networks:
      - net
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: .
          target: /app
  db:
    image: postgres:latest
    networks:
      - net
    environment:
      POSTGRES_USER: sigap
      POSTGRES_DB: sigap_bd
      POSTGRES_PASSWORD: sigap
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
